// flags.js
export const countryEmojis = {
  "United Kingdom": "🇬🇧",
  "Germany": "🇩🇪",
  "United States": "🇺🇸",
  "USA": "🇺🇸",
  "France": "🇫🇷",
  "Spain": "🇪🇸",
  "Italy": "🇮🇹",
  "Netherlands": "🇳🇱",
  "Australia": "🇦🇺",
  "Canada": "🇨🇦",
  "Brazil": "🇧🇷",
  "Monaco": "🇲🇨",
  "Japan": "🇯🇵",
  "Thailand": "🇹🇭",
  "New Zealand": "🇳🇿",
  "Argentina": "🇦🇷",
  "China": "🇨🇳",
  "Finland": "🇫🇮",
  "Gay": "🏳️‍🌈",
  "Switzerland": "🇨🇭",
  "Ireland": "🇮🇪",
  "Morocco": "🇲🇦",
  "Mexico": "🇲🇽" ,
  "Portugal": "🇵🇹",
  "Bahrain": "🇧🇭",
  "Azerbaijan": "🇦🇿",
  "India": "🇮🇳",
  "Belgium": "🇧🇪",
  "Hungary": "🇭🇺",
  "Turkey": "🇹🇷",
  "Saudi Arabia": "🇸🇦",
  "South Africa": "🇿🇦",
  "South Korea": "🇰🇷",
  "Qatar": "🇶🇦",
  "Singapore": "🇸🇬",
  "Austria": "🇦🇹", 
  "Sweden": "🇸🇪",
  "Malaysia": "🇲🇾",
  "Russia": "🇷🇺",
  "United Arab Emirates": "🇦🇪",
  "Great Britain": "🇬🇧"
};
